<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>hruh_control</name>
  <version>0.1.0</version>
  <description>ros2_control controller configuration for the HRUH humanoid (legs, head, arms, hands; rigid torso).</description>
  <maintainer email="shreyaspatel0456@gmail.com">shreyas</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>position_controllers</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>mock_components</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
