<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />
    <xacro:include filename="arm.xacro" />
    <xacro:include filename="arm_gazebo.xacro" />
    <xacro:include filename="hruh.xacro" />

    <joint name="mobile_base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length / 10.0} 0 ${base_height}" rpy="0 0 3.14" />
    </joint>

    <!-- <joint name="arm_chest_joint" type="fixed">
        <parent link="forearm_link" />
        <child link="chest_hruh" />
        <origin xyz="${base_length / 50.0} 0 ${-forearm_length/4}" rpy="0 0 0" />
    </joint> -->

    
    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <robot_param>robot_description</robot_param>
            <parameters>$(find my_robot_description)/config/controllers.yaml</parameters>
        </plugin>
    </gazebo>

    

    <xacro:include filename="camera.xacro" />

</robot>