controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    left_full_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
      - chest_to_left_shoulder
      - left_shoulder_to_bisecp
      - left_elbow_inword_to_midle
      - left_forarm_to_wrist
      - left_palm_to_thomb
      - left_thomb_to_thomb_middle
      - left_thomb_middle_to_thomb_upper
      - left_palm_to_finger1_lower
      - left_palm_to_finger2_lower
      - left_palm_to_finger3_lower
      - left_palm_to_finger4_lower
      - left_finger1_lower_to_finger1_middle
      - left_finger2_lower_to_finger2_middle
      - left_finger3_lower_to_finger3_middle
      - left_finger4_lower_to_finger4_middle
      - left_finger1_middle_to_finger1_upper
      - left_finger2_middle_to_finger2_upper
      - left_finger3_middle_to_finger3_upper
      - left_finger4_middle_to_finger4_upper
      state_publish_rate: 50
      action_monitor_rate: 20
      command_interfaces:
      - position
      state_interfaces:
      - position
      - velocity
      allow_partial_joints_goal: false
      constraints:
        goal_time: 2.0
        stopped_velocity_tolerance: 0.1
